services:
  mysql-auth:
    image: mysql:8.0
    container_name: mysql_auth
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_DATABASE: auth_service
      MYSQL_USER: auth_user
      MYSQL_PASSWORD: 12345
    ports:
      - "3307:3306"
    volumes:
      - ./data/auth:/var/lib/mysql
      - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
